export const stanbicIBTCBranches = [
  {
    label: "Aba Main",
    value: "ABA_MAIN",
    address: "7, ABA-OWERRI ROAD P.M.B 7477, ABA",
    city: "Aba",
    state: "Abia",
  },
  {
    label: "Aba Road Building",
    value: "ABA_ROAD_BUILDING",
    address: "171, ABA ROAD, PORT HARCOURT RIVERS STATE",
    city: "Aba Road",
    state: "Rivers",
  },
  {
    label: "Abakaliki",
    value: "ABAKALIKI",
    address: "10 OGOJA ROAD",
    city: "Abakaliki",
    state: "Ebonyi",
  },
  {
    label: "Abeokuta",
    value: "ABEOKUTA",
    address: "2A, LANTORO ROAD ISALE AKE",
    city: "Abeokuta",
    state: "Ogun",
  },
  {
    label: "Abuja Service Centre",
    value: "ABUJA_SERVICE_CENTRE",
    address: "NO. 75, RALPH SHODEINDE STREET",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Abuja-Nnpc",
    value: "ABUJA-NNPC",
    address: "NNPC TOWER, HERBERT MACAULAY WAY, GARKI, ABUJA",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Abule-Egba",
    value: "ABULE-EGBA",
    address: "633 LAGOS ABEOKUTA EXPRESSWAYS",
    city: "Abule - Egba",
    state: "Lagos",
  },
  {
    label: "Ado Ekiti",
    value: "ADO_EKITI",
    address: "ADO EKITI - IYIN EXPRESS/SECRETARIAT ROAD",
    city: "Ado Ekiti",
    state: "Ekiti",
  },
  {
    label: "Afribank Street",
    value: "AFRIBANK_STREET",
    address: "CHURCHGATE BUILDING PC 30, AFRIBANK STREET",
    city: "Victoria Island",
    state: "Lagos",
  },
  {
    label: "Agbara",
    value: "AGBARA",
    address: "AGBARA ESTATE SHOPPING COMPLEX AGBARA OGUN",
    city: "Agbara",
    state: "Ogun",
  },
  {
    label: "Agodi Gate Mini",
    value: "AGODI_GATE_MINI",
    address: "INAOLAJI BUSINESS COMPLEX, AGODI GATE",
    city: "Agodi",
    state: "Oyo",
  },
  {
    label: "Aguda",
    value: "AGUDA",
    address: "1/3 ENITAN STREET, AGUDA, SURULERE",
    city: "Aguda, Surulere",
    state: "Lagos",
  },
  {
    label: "Ahmadu Bello Way",
    value: "AHMADU_BELLO_WAY",
    address: "PLOT 149 AHMADU BELLO WAY, AREA 11 GARKI ABUJA",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Airport Road - Warri",
    value: "AIRPORT_ROAD_-_WARRI",
    address: "23 OGUNU - AIRPORT ROAD, WARRI",
    city: "Warri",
    state: "Delta",
  },
  {
    label: "Ajah Mini",
    value: "AJAH_MINI",
    address: "4A MEGAWAVES PLAZA ADDO ROUND ABOUT",
    city: "Ajah",
    state: "Lagos",
  },
  {
    label: "Ajose Adeogun Branch",
    value: "AJOSE_ADEOGUN_BRANCH",
    address: "290E, AJOSE ADEOGUN STREET",
    city: "Victoria Island",
    state: "Lagos",
  },
  {
    label: "Akoka",
    value: "AKOKA",
    address: "100, FINBARR S ROAD AKOKA, YABA LAGOS",
    city: "Akoka, Yaba",
    state: "Lagos",
  },
  {
    label: "Akure",
    value: "AKURE",
    address: "GREAT NIGERIA INSURANCE HOUSE",
    city: "Akure",
    state: "Ondo",
  },
  {
    label: "Alaba",
    value: "ALABA",
    address: "H48/H49 ALABA INTERNATIONAL MARKET",
    city: "Alaba, Lagos",
    state: "Lagos",
  },
  {
    label: "Alausa",
    value: "ALAUSA",
    address:
      "NIESV BUILDING, PLOT A, BLOCK 12, ELEPHANT CEMENT WAY, OPPOSITE LAGOS STATE SECRETARIAT MOSQUE, CENTRAL BUSINESS DISTRICT ALAUSA, IKEJA, LAGOS",
    city: "Alausa",
    state: "Lagos",
  },
  {
    label: "Allen Avenue",
    value: "ALLEN_AVENUE",
    address: "31, ALLEN AVENUE, IKEJA",
    city: "Allen Avenue",
    state: "Lagos",
  },
  {
    label: "Ariaria Mini",
    value: "ARIARIA_MINI",
    address: "189, FAULKS ROAD, ARIARIA MARKET, ABA",
    city: "Aba",
    state: "Abia",
  },
  {
    label: "Artillery",
    value: "ARTILLERY",
    address: "234, ABA PHC ROAD",
    city: "Artillery",
    state: "Rivers",
  },
  {
    label: "Asaba",
    value: "ASABA",
    address: "206 NNEBISI ROAD ASABA",
    city: "Asaba",
    state: "Delta",
  },
  {
    label: "Awka",
    value: "AWKA",
    address: "49 ZIKS AVENUE AWKA",
    city: "Awka",
    state: "Anambra",
  },
  {
    label: "Awolowo Road",
    value: "AWOLOWO_ROAD",
    address: "85, AWOLOWO ROAD IKOYI",
    city: "Ikoyi",
    state: "Lagos",
  },
  {
    label: "Balogun Business Association Plaza",
    value: "BALOGUN_BUSINESS_ASSOCIATION_PLAZA",
    address: "3A, PORTION C OPPOSITE SOKOTO PLAZA BBA TRADE FAIR, OJO, LAGOS",
    city: "Trade Fair, Ojo",
    state: "Lagos",
  },
  {
    label: "Bauchi",
    value: "BAUCHI",
    address: "16, YANDOKA ROAD",
    city: "Bauchi",
    state: "Bauchi",
  },
  {
    label: "Benin City",
    value: "BENIN_CITY",
    address: "71, AKPAKPAVA STREET",
    city: "Benin",
    state: "Edo",
  },
  {
    label: "Broad Street Branch",
    value: "BROAD_STREET_BRANCH",
    address: "143, BROAD STREET",
    city: "Lagos Island",
    state: "Lagos",
  },
  {
    label: "Calabar",
    value: "CALABAR",
    address: "71, NDIDEM USANG ISO ROAD",
    city: "Calabar",
    state: "Cross River",
  },
  {
    label: "Challenge",
    value: "CHALLENGE",
    address: "127, NIGER WEST ROAD, ORITA CHALLENGE, IBADAN",
    city: "Challenge",
    state: "Oyo",
  },
  {
    label: "Damaturu",
    value: "DAMATURU",
    address: "PLOT 591A, NJIWAJI LAYOUT DAMATURU",
    city: "Damaturu",
    state: "Yobe",
  },
  {
    label: "Deide Mini",
    value: "DEIDE_MINI",
    address: "DEIDE MARKET ROAD, OPPOSITE THE MARKET, DEIDE, ABUJA",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Dutse",
    value: "DUTSE",
    address: "SANNI ABACHA WAY DUTSE, JIGAWA",
    city: "Dutse",
    state: "Jigawa",
  },
  {
    label: "Egbeda",
    value: "EGBEDA",
    address: "38, SHASHA ROAD EGBEDA, LAGOS",
    city: "Egbeda",
    state: "Lagos",
  },
  {
    label: "Eket",
    value: "EKET",
    address: "EKET TOWN/2 GRACE BILL ROAD, EKET",
    city: "Eket",
    state: "Akwa Ibom",
  },
  {
    label: "Eleme Cash Center",
    value: "ELEME_CASH_CENTER",
    address: "IEPPL COMPLEX EAST WEST ROAD PORT HARCOURT",
    city: "Port Harcourt",
    state: "Rivers",
  },
  {
    label: "Enugu",
    value: "ENUGU",
    address: "252, OGUI ROAD, EBEANO HOUSING ESTATE",
    city: "Enugu",
    state: "Enugu",
  },
  {
    label: "Festac",
    value: "FESTAC",
    address: "23 ROAD, FESTAC TOWN",
    city: "Festac, Lagos",
    state: "Lagos",
  },
  {
    label: "Garki (Area 3)",
    value: "GARKI_(AREA_3)",
    address: "INFINITY HOUSE, 11 KAURA NAMODA STREET",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Gbagada",
    value: "GBAGADA",
    address: "15, DIYA STREET, IFAKO, GBAGADA, LAGOS",
    city: "Gbagada",
    state: "Lagos",
  },
  {
    label: "Gbagi (Ibadan)",
    value: "GBAGI_(IBADAN)",
    address: "NO. 1, LEBANON STREET, AJE HOUSE",
    city: "Gbagi",
    state: "Oyo",
  },
  {
    label: "Gboko",
    value: "GBOKO",
    address: "NO. 37, CAPTAIN DOWNES ROAD",
    city: "Gboko",
    state: "Benue",
  },
  {
    label: "Gombe",
    value: "GOMBE",
    address: "22, BIU ROAD GOMBE",
    city: "Gombe",
    state: "Gombe",
  },
  {
    label: "Gusau",
    value: "GUSAU",
    address: "10, SANNI ABACHA ROAD GUSAU",
    city: "Gusau",
    state: "Zamfara",
  },
  {
    label: "Gwagwalada",
    value: "GWAGWALADA",
    address: "PLOT 415, SPECIALIST HOSPITAL ROAD GWAGWALADA",
    city: "Gwagwalada",
    state: "Abuja",
  },
  {
    label: "Head Office Branch - Ibtc Place",
    value: "HEAD_OFFICE_BRANCH_-_IBTC_PLACE",
    address: "I.B.T.C PLACE WALTER CARRINGTON",
    city: "Victoria Island",
    state: "Lagos",
  },
  {
    label: "Herbert Macaulay",
    value: "HERBERT_MACAULAY",
    address: "220, HERBERT MACAULAY WAY YABA",
    city: "Yaba",
    state: "Lagos",
  },
  {
    label: "Hotoro Mini",
    value: "HOTORO_MINI",
    address: "4, MAIDUGURI ROAD, KANO",
    city: "Hotoro",
    state: "Kano",
  },
  {
    label: "Ibadan Main",
    value: "IBADAN_MAIN",
    address: "TOTAL GARDEN, UCH/SECRETARIAT ROAD, AGODI",
    city: "Agodi",
    state: "Oyo",
  },
  {
    label: "Idejo",
    value: "IDEJO",
    address: "1712 IDEJO STREET VICTORIA ISLAND, LAGOS",
    city: "Victoria Island",
    state: "Lagos",
  },
  {
    label: "Idumagbo",
    value: "IDUMAGBO",
    address: "61A, IDUMAGBO AVENUE, LAGOS ISLAND",
    city: "Lagos Island",
    state: "Lagos",
  },
  {
    label: "Ife",
    value: "IFE",
    address: "5, OBALUFON-LAGERE ROAD, CATHOLIC LAGERE",
    city: "Ife",
    state: "Osun",
  },
  {
    label: "Igando",
    value: "IGANDO",
    address: "51, LASU-IBA ROAD, IGANDO LAGOS",
    city: "Igando, Lagos",
    state: "Lagos",
  },
  {
    label: "Ijebu Ode",
    value: "IJEBU_ODE",
    address: "58, IBADAN ROAD IJEBU ODE",
    city: "Ijebu Ode",
    state: "Ogun",
  },
  {
    label: "Ikeja City Mall",
    value: "IKEJA_CITY_MALL",
    address: "SHOP L55, IKEJA CITY MALL, ALAUSA, IKEJA, LAGOS",
    city: "Ikeja",
    state: "Lagos",
  },
  {
    label: "Ikeja Service Centre",
    value: "IKEJA_SERVICE_CENTRE",
    address: "43, OPEBI ROAD, IKEJA",
    city: "Ikeja",
    state: "Lagos",
  },
  {
    label: "Ikorodu",
    value: "IKORODU",
    address: "108, LAGOS ROAD IKORODU",
    city: "Ikorodu",
    state: "Lagos",
  },
  {
    label: "Ikota",
    value: "IKOTA",
    address: "194, IKOTA SHOPPING COMPLEX",
    city: "Ikota",
    state: "Lagos",
  },
  {
    label: "Ikotun Branch",
    value: "IKOTUN_BRANCH",
    address: "45, IDIMU ROAD, IKOTUN, LAGOS STATE",
    city: "Ikotun",
    state: "Lagos",
  },
  {
    label: "Ilesha",
    value: "ILESHA",
    address: "A198, OSOGBO ROAD, ISOKUN, ILESHA",
    city: "Ilesha",
    state: "Osun",
  },
  {
    label: "Ilorin",
    value: "ILORIN",
    address: "13 UNITY ROAD, OPPOSITE UNITED SECONDARY SCHOOL, ILORIN, KWARA STATE",
    city: "Ilorin",
    state: "Kwara",
  },
  {
    label: "Ipaja Branch",
    value: "IPAJA_BRANCH",
    address: "142, IPAJA ROAD, BARUWA",
    city: "Ipaja",
    state: "Lagos",
  },
  {
    label: "Iwo Road (Ibadan)",
    value: "IWO_ROAD_(IBADAN)",
    address: "NO 32, IWO ROAD",
    city: "Iwo",
    state: "Oyo",
  },
  {
    label: "Iwo Town",
    value: "IWO_TOWN",
    address: "147, EJIGBO ROAD, ARAROMI SABO, IWO TOWN",
    city: "Iwo Town",
    state: "Osun",
  },
  {
    label: "Iyana Church",
    value: "IYANA_CHURCH",
    address: "IBITOLA PLAZA, IYANA CHURCH IBADAN",
    city: "Iyana Church, Ibadan",
    state: "Oyo",
  },
  {
    label: "Jalingo",
    value: "JALINGO",
    address: "22, HAMMARUWA WAY JALINGO",
    city: "Jalingo",
    state: "Taraba",
  },
  {
    label: "Jos",
    value: "JOS",
    address: "34 AHMADU BELLO WAY JOS",
    city: "Jos",
    state: "Plateau",
  },
  {
    label: "Kachia Mini",
    value: "KACHIA_MINI",
    address: "7A, KACHIA ROAD KADUNA",
    city: "Kachia",
    state: "Kaduna",
  },
  {
    label: "Kaduna Central Mini",
    value: "KADUNA_CENTRAL_MINI",
    address: "1 BAYAJIDA ROAD, CENTRAL MARKET, KADUNA NORTH",
    city: "Kaduna",
    state: "Kaduna",
  },
  {
    label: "Kaduna Main",
    value: "KADUNA_MAIN",
    address: "14 AHMADU BELLO WAY KADUNA",
    city: "Kaduna",
    state: "Kaduna",
  },
  {
    label: "Kaduna Nnpc",
    value: "KADUNA_NNPC",
    address: "NNPC REFINERY COMPLEX KADUNA",
    city: "Kaduna",
    state: "Kaduna",
  },
  {
    label: "Kano",
    value: "KANO",
    address: "13E, BELLO ROAD, KANO",
    city: "Kano",
    state: "Kano",
  },
  {
    label: "Kano Service Centre",
    value: "KANO_SERVICE_CENTRE",
    address: "3, BANK ROAD",
    city: "Kano",
    state: "Kano",
  },
  {
    label: "Kantin Kwari",
    value: "KANTIN_KWARI",
    address: "71A, FAGEE TAKUDU ROAD",
    city: "Kantin Kwari",
    state: "Kano",
  },
  {
    label: "Katsina",
    value: "KATSINA",
    address: "193, IBB WAY",
    city: "Katsina",
    state: "Katsina",
  },
  {
    label: "Kawo-Mando",
    value: "KAWO-MANDO",
    address: "KAWO ZARIA ROAD, KAWO MARKET",
    city: "Kawo Mando",
    state: "Kaduna",
  },
  {
    label: "Kebbi",
    value: "KEBBI",
    address: "PLOT 69, AHMADU BELLO WAY, BIRNIN KEBBI",
    city: "Kebbi",
    state: "Kebbi",
  },
  {
    label: "Ketu Mini",
    value: "KETU_MINI",
    address: "463, IKORODU ROAD KETU",
    city: "Ketu",
    state: "Lagos",
  },
  {
    label: "Kontangora",
    value: "KONTANGORA",
    address: "LAGOS - KADUNA ROAD KONTANGORA",
    city: "Kontagora",
    state: "Niger",
  },
  {
    label: "Kubwa Mini",
    value: "KUBWA_MINI",
    address: "84/85 GADO NASKO WAY, KUBWA, ABUJA",
    city: "Kubwa",
    state: "Abuja",
  },
  {
    label: "Lafia",
    value: "LAFIA",
    address: "PLOT 1, JOS ROAD OPP. FATIMA HOUSE",
    city: "Lafia",
    state: "Nassarawa",
  },
  {
    label: "Lagos Service Centre",
    value: "LAGOS_SERVICE_CENTRE",
    address: "PLOT 1321B KARIMU KOTUN STREET",
    city: "Victoria Island",
    state: "Lagos",
  },
  {
    label: "Lekki 1 (Freedom Way)",
    value: "LEKKI_1_(FREEDOM_WAY)",
    address: "PLOT 41, LEKKI FREEDOM WAY LEKKI, LAGOS",
    city: "Lekki",
    state: "Lagos",
  },
  {
    label: "Lekki 2",
    value: "LEKKI_2",
    address: "KM 18, LEKKI - EPE EXPRESSWAY, AGUNGI, LAGOS",
    city: "Lekki",
    state: "Lagos",
  },
  {
    label: "Lekki Admiralty",
    value: "LEKKI_ADMIRALTY",
    address:
      "1, BABATUNDE MASHA STREET, BY ROAD 10, LEKKI ADMIRALTY WAY, LEKKI PHASE 1, LEKKI LAGOS",
    city: "Lekki",
    state: "Lagos",
  },
  {
    label: "Lokoja",
    value: "LOKOJA",
    address: "IBB WAY OPP. KOGI STATE NEW SPECIALIST HOSPITAL",
    city: "Lokoja",
    state: "Kogi",
  },
  {
    label: "Maiduguri",
    value: "MAIDUGURI",
    address: "9/10 KIRIKASAMA ROAD MAIDUGURI",
    city: "Maiduguri",
    state: "Borno",
  },
  {
    label: "Maitama",
    value: "MAITAMA",
    address: "PLOT 2777, CADASTRAL ZONE A6 P.M.B 337, ABUJA",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Makurdi",
    value: "MAKURDI",
    address: "NO. 5, OGIRI OKO ROAD, MAKURDI",
    city: "Makurdi",
    state: "Benue",
  },
  {
    label: "Mararaba Mini",
    value: "MARARABA_MINI",
    address: "KWAD SHOPPING COMPLEX MARARABA KEFFI ROAD",
    city: "Mararaba",
    state: "Nassarawa",
  },
  {
    label: "Maryland Branch",
    value: "MARYLAND_BRANCH",
    address: "10, MOBOLAJI BANK ANTHONY WAY, MARYLAND",
    city: "Maryland",
    state: "Lagos",
  },
  {
    label: "Minna",
    value: "MINNA",
    address: "BOSSO ROAD, BESIDE CENTRAL MOSQUE",
    city: "Minna",
    state: "Niger",
  },
  {
    label: "Mokola",
    value: "MOKOLA",
    address: "18B, OYO ROAD, MOKOLA IBADAN",
    city: "Mokola",
    state: "Oyo",
  },
  {
    label: "Muritala Mohammed Airport",
    value: "MURITALA_MOHAMMED_AIRPORT",
    address: "NAHCO COMPLEX OFF MMIA",
    city: "Muritala Mohammed Airport",
    state: "Lagos",
  },
  {
    label: "Mushin",
    value: "MUSHIN",
    address: "103, LADIPO MUSHIN STREET",
    city: "Mushin",
    state: "Lagos",
  },
  {
    label: "Nigerian Immigration Service",
    value: "NIGERIAN_IMMIGRATION_SERVICE",
    address: "NIGERIAN IMMIGRATION HEADQUARTERS, AIRPORT RD",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Nigerian Ports Authority",
    value: "NIGERIAN_PORTS_AUTHORITY",
    address: "ACCOUNT BLOCK, NIGERIAN PORTS AUTHORITY, APAPA",
    city: "Apapa, Lagos",
    state: "Lagos",
  },
  {
    label: "Oba Akran Avenue",
    value: "OBA_AKRAN_AVENUE",
    address: "20 OBA AKRAN AVENUE, IKEJA",
    city: "Ikeja",
    state: "Lagos",
  },
  {
    label: "Ogba",
    value: "OGBA",
    address: "32, IJAIYE ROAD OGBA",
    city: "Ogba",
    state: "Lagos",
  },
  {
    label: "Ogbomosho",
    value: "OGBOMOSHO",
    address: "OGBOMOSHO, ILORIN ROAD OGBOMOSHO",
    city: "Ogbomosho",
    state: "Oyo",
  },
  {
    label: "Ogudu",
    value: "OGUDU",
    address: "54, OGUDU OJOTA ROAD",
    city: "Ogudu",
    state: "Lagos",
  },
  {
    label: "Ojatuntun",
    value: "OJATUNTUN",
    address: "171 ABDULAZEEZ ATTAH ROAD",
    city: "Ojatuntun",
    state: "Kwara",
  },
  {
    label: "Ojodu",
    value: "OJODU",
    address: "102 ISHERI ROAD OJODU BERGER",
    city: "Ojodu",
    state: "Lagos",
  },
  {
    label: "Ojuwoye Mini",
    value: "OJUWOYE_MINI",
    address: "214, AGEGE MOTOR ROAD MUSHIN",
    city: "Ojuwoye",
    state: "Lagos",
  },
  {
    label: "Oke Arin Mini",
    value: "OKE_ARIN_MINI",
    address: "120, ALAKORO STREET OKE ARIN",
    city: "Lagos Island",
    state: "Lagos",
  },
  {
    label: "Oko Oba Mini",
    value: "OKO_OBA_MINI",
    address: "327 OLD ABEOKUTA ROAD, OKO OBA, LAGOS",
    city: "Oko Oba",
    state: "Lagos",
  },
  {
    label: "Okota",
    value: "OKOTA",
    address: "1 ALHAJI ADENEKAN STREET",
    city: "Okota",
    state: "Lagos",
  },
  {
    label: "Olu Obasanjo P/H",
    value: "OLU_OBASANJO_P/H",
    address: "58, OLUOBASANJO ROAD",
    city: "Olu-Obasanjo",
    state: "Rivers",
  },
  {
    label: "Ondo",
    value: "ONDO",
    address: "62, YABA ROAD, ONDO",
    city: "Ondo",
    state: "Ondo",
  },
  {
    label: "Onitsha",
    value: "ONITSHA",
    address: "13, BRIGHT STREET ONITSHA",
    city: "Onitsha",
    state: "Anambra",
  },
  {
    label: "Orile Coker",
    value: "ORILE_COKER",
    address: "104 MARKET STREET",
    city: "Orile Coker",
    state: "Lagos",
  },
  {
    label: "Oshodi",
    value: "OSHODI",
    address: "PLOT 14A OSHODI-APAPA EXPRESSWAY",
    city: "Oshodi",
    state: "Lagos",
  },
  {
    label: "Oshogbo",
    value: "OSHOGBO",
    address: "201 GBOGAN - IBADAN ROAD",
    city: "Oshogbo",
    state: "Osun",
  },
  {
    label: "Osolo",
    value: "OSOLO",
    address: "61 OSOLO WAY ASCON FILLING",
    city: "Osolo",
    state: "Lagos",
  },
  {
    label: "Otukpo",
    value: "OTUKPO",
    address: "ENUGU - MAKURDI ROAD, OTUKPO",
    city: "Otukpo",
    state: "Benue",
  },
  {
    label: "Owerri",
    value: "OWERRI",
    address: "NO. 81, OKIGWE ROAD",
    city: "Owerri",
    state: "Imo",
  },
  {
    label: "Oyo",
    value: "OYO",
    address: "OYO-OGBOMOSO ROAD OYO TOWN",
    city: "Oyo",
    state: "Oyo",
  },
  {
    label: "Port Harcourt Service Centre",
    value: "PORT_HARCOURT_SERVICE_CENTRE",
    address: "133A OLU OBASANJO ROAD, GRA",
    city: "Port Harcourt",
    state: "Rivers",
  },
  {
    label: "Ring Road",
    value: "RING_ROAD",
    address: "1B, MOSHOOD ABIOLA WAY RING ROAD, IBADAN",
    city: "Ibadan",
    state: "Oyo",
  },
  {
    label: "Sabon Gari-Kano",
    value: "SABON_GARI-KANO",
    address: "1, GALADIMA ROAD SABON GARI-KANO",
    city: "Sabon Gari",
    state: "Kano",
  },
  {
    label: "Sabon Tasha",
    value: "SABON_TASHA",
    address: "32, KACHIA ROAD, SABON TASHA KADUNA",
    city: "Sabon Tasha",
    state: "Kaduna",
  },
  {
    label: "Saki",
    value: "SAKI",
    address: "ILESHA-IBARUBA ROAD, OPP. SAKI WEST LOCAL GOVT.",
    city: "Saki",
    state: "Oyo",
  },
  {
    label: "Sango-Otta",
    value: "SANGO-OTTA",
    address: "2 KM 38, ABEOKUTA EXPRESSWAY",
    city: "Sango Otta",
    state: "Ogun",
  },
  {
    label: "Sapele Road",
    value: "SAPELE_ROAD",
    address: "131A, SAPELE ROAD, SAPELE",
    city: "Sapele",
    state: "Edo",
  },
  {
    label: "Satellite",
    value: "SATELLITE",
    address: "389, OLD OJO ROAD",
    city: "Satellite, Lagos",
    state: "Lagos",
  },
  {
    label: "Shagamu",
    value: "SHAGAMU",
    address: "167, AKARIGO ROAD SHAGAMU",
    city: "Shagamu",
    state: "Ogun",
  },
  {
    label: "Shauchi",
    value: "SHAUCHI",
    address: "1 RIMI QUARTERS, UMMA BAYERO ROAD KANO",
    city: "Shaushi",
    state: "Kano",
  },
  {
    label: "Shomolu",
    value: "SHOMOLU",
    address: "22, MARKET STREET SHOMOLU LAGOS",
    city: "Shomolu",
    state: "Lagos",
  },
  {
    label: "Sokoto",
    value: "SOKOTO",
    address: "8, MAIDUGURI ROAD P.M.B 2375",
    city: "Sokoto",
    state: "Sokoto",
  },
  {
    label: "Suleja",
    value: "SULEJA",
    address: "MINNA ROAD, OPPOSITE FORCE A DIVISION, SULEJA",
    city: "Suleja",
    state: "Niger",
  },
  {
    label: "Surulere",
    value: "SURULERE",
    address: "84 ADENIRAN OGUNSANYA STREET",
    city: "Surulere",
    state: "Lagos",
  },
  {
    label: "Tejuosho",
    value: "TEJUOSHO",
    address: "77, OJUELEGBA ROAD, YABA LAGOS",
    city: "Tejuosho",
    state: "Lagos",
  },
  {
    label: "Tower Mall",
    value: "TOWER_MALL",
    address: "SHOP 10, GRAND TOWER, ABUJA MALL, APO, ABUJA",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Toyin Street",
    value: "TOYIN_STREET",
    address: "36A, TOYIN STREET, IKEJA P.M.B.21778, IKEJA",
    city: "Ikeja",
    state: "Lagos",
  },
  {
    label: "Trade Fair",
    value: "TRADE_FAIR",
    address: "OBASANJO HALL/HALL 2 ASPAMDA PLAZA",
    city: "Trade Fair, Ojo",
    state: "Lagos",
  },
  {
    label: "Trans Amadi - P/H",
    value: "TRANS_AMADI_-_P/H",
    address: "7, TRANS-AMADI ROAD",
    city: "Trans-Amadi",
    state: "Rivers",
  },
  {
    label: "Trans Amadi 2 Branch",
    value: "TRANS_AMADI_2_BRANCH",
    address: "87, TRANS AMADI",
    city: "Trans-Amadi",
    state: "Rivers",
  },
  {
    label: "Ui Road",
    value: "UI_ROAD",
    address: "SAYORA BUILDING, UI ROAD OPP UI SECOND GATE",
    city: "Ibadan",
    state: "Oyo",
  },
  {
    label: "Umuahia",
    value: "UMUAHIA",
    address: "2 MARKET ROAD BY LIBRARY AVENUE, UMUAHIA",
    city: "Umuahia",
    state: "Abia",
  },
  {
    label: "Uniben",
    value: "UNIBEN",
    address: "UNIVERSITY OF BENIN, UGBOWO CAMPUS, BENIN",
    city: "Benin",
    state: "Edo",
  },
  {
    label: "Uyo Branch",
    value: "UYO_BRANCH",
    address: "65B NWANIBA ROAD",
    city: "Uyo",
    state: "Akwa Ibom",
  },
  {
    label: "Warehouse Road, Apapa",
    value: "WAREHOUSE_ROAD,_APAPA",
    address: "10/12, WAREHOUSE ROAD APAPA, LAGOS",
    city: "Apapa, Lagos",
    state: "Lagos",
  },
  {
    label: "Warri",
    value: "WARRI",
    address: "98, EFFURUN-SAPELE ROAD",
    city: "Warri",
    state: "Delta",
  },
  {
    label: "Wuse 2",
    value: "WUSE_2",
    address: "PLOT 1387 AMINU KANO CRESCENT, WUSE II, ABUJA",
    city: "Abuja",
    state: "Abuja",
  },
  {
    label: "Yenegoa",
    value: "YENEGOA",
    address: "623, MBIAMA-YENEGOA ROAD, YENEGOA",
    city: "Yenagoa",
    state: "Bayelsa",
  },
  {
    label: "Yola",
    value: "YOLA",
    address: "1, MUHAMMED MUSTAPHA WAY, JIMETA",
    city: "Yola",
    state: "Adamawa",
  },
  {
    label: "Zaria",
    value: "ZARIA",
    address: "4, PARK ROAD ZARIA/PARK",
    city: "Zaria",
    state: "Kaduna",
  },
  {
    label: "Zaria City Mini",
    value: "ZARIA_CITY_MINI",
    address: "90, ANGUNWA MALLAM SULE, BAKIN KASUWA",
    city: "Zaria City Mini/Bakin",
    state: "Kaduna",
  },
];
